"""Initial Migration

Revision ID: 7ebae7278158
Revises: c984bd5ccad2
Create Date: 2019-02-28 12:40:21.734374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebae7278158'
down_revision = 'c984bd5ccad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('Description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###
